#!/usr/bin/env python

import numpy as np
import cv2
#from time import clock
import sys
from collections import deque

import video

if __name__ == '__main__':
	
    try: fn = sys.argv[1]
    except: fn = 0
    cam = video.create_capture(fn, fallback='synth:bg=../cpp/baboon.jpg:class=chess:noise=0.05')
    
    picturebuffer = deque()
    for i in range(100):
		flag, frame = cam.read()
		picturebuffer.append(frame)
		
    while True:
        flag, frame = cam.read()
        picturebuffer.append(frame)
        cv2.imshow('camera', picturebuffer.popleft() )
        
        ch = 0xFF & cv2.waitKey(1)
        if ch == ord('q'):
            break
    cv2.destroyAllWindows()
